export default {
  products: [
    {
      _id: "1",
      name: "Switch Sticker",
      category: "Sticker",
      image: "./sticker-switch.jpg",
      price: 3,
      description: "Handmade",
      rating: 5.0,
      numReviews: 10,
      countInStock: 50,
    },
    {
      _id: "2",
      name: "Butterfly Sticker",
      category: "Sticker",
      image: "./butterfly-sticker.jpg",
      price: 3,
      description: "Handmade",
      rating: 5.0,
      numReviews: 15,
      countInStock: 40,
    },
    {
      _id: "3",
      name: "Holographic Butterfly Sticker",
      category: "Sticker",
      image: "./butterfly-holographic.jpg",
      price: 3,
      description: "Handmade",
      rating: 5.0,
      numReviews: 15,
      countInStock: 50,
    },
    {
      _id: "4",
      name: "Queen of JS Button",
      category: "Button",
      image: "./queenjs.jpg",
      price: 2,
      description: "Handmade",
      rating: 4.8,
      numReviews: 8,
      countInStock: 20,
    },
    {
      _id: "5",
      name: "CSS Goddess Button",
      category: "Button",
      image: "./css.jpg",
      price: 2,
      description: "Handmade",
      rating: 4.8,
      numReviews: 8,
      countInStock: 20,
    },
    {
      _id: "6",
      name: "API Fairy Button",
      category: "Button",
      image: "./fairy-button.jpg",
      price: 2,
      description: "Handmade",
      rating: 4.8,
      numReviews: 8,
      countInStock: 20,
    },
    {
      _id: "7",
      name: "WordPress Empress Button",
      category: "Button",
      image: "./wp-circle1.jpg",
      price: 2,
      description: "Handmade",
      rating: 4.8,
      numReviews: 8,
      countInStock: 20,
    },
  ],
};
